/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CascaderField: typeof import('./src/components/CascaderField.vue')['default']
    CellField: typeof import('./src/components/CellField.vue')['default']
    CheckboxField: typeof import('./src/components/CheckboxField.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    DateField: typeof import('./src/components/DateField.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    RadioField: typeof import('./src/components/RadioField.vue')['default']
    VanCascader: typeof import('vant/es')['Cascader']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
